name: learning_app
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0<3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  http: "0.11.3+17"
  intl: ^0.15.7
  image_picker:
  firebase_database:
  firebase_storage:
  animated_text_kit: ^1.3.0
  firebase_core: ^0.4.4+3
  firebase_auth: ^0.15.5+2
  cloud_firestore: ^0.13.4+2
  #cloud_firestore: ^0.13.7
  modal_progress_hud: ^0.1.3
#  file_picker: ^1.13.2
#  file_picker: ^1.3.6
  file_picker: ^1.1.1


  #firebase_analytics: ^0.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - images/

